include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/src/product_health_home.dart
  errors:
    invalid_use_of_visible_for_testing_member: ignore

linter:
  rules:
    avoid_print: true
    use_build_context_synchronously: true
